import java.time.LocalTime

/*Documentation: https://jenkinsci.github.io/job-dsl-plugin */

job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${LocalTime.now()}, the project is a small Maven project hosted on github")
    scm {
        git("https://github.com/zikozee/Jenkins_Upgradev3.git", 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'maven-samples/single-module/pom.xml')
    }
    publishers {
        //archive the jar file generated
        archiveArtifacts '**/*.jar'
    }
}